config/routes.rb
FragmentsProject::Application.routes.draw do

  resources :libraries

  get 'themes/choose/:page_id', to: 'themes#choose', as: 'choose_theme'
  resources :themes

  resources :menu_entries
  match 'menu_entries/:id/move', to: 'menu_entries#move', as: 'move_menu_entry'
  
  get "puzzle_box/show"

  root to: 'static_pages#home'
  
  resources :users
  resources :user_role_relationships, only: [:create, :destroy]
  resources :sessions, only:[:new,:create,:destroy]
  
  match 'articles/:id/set_cover_fragment/', to: 'articles#set_cover_fragment', as: 'set_article_cover'
  resources :articles
  match 'articles/:id/publish', to: 'articles#publish', as: 'publish_article'
  match 'articles/:id/unpublish', to: 'articles#unpublish', as: 'unpublish_article'
  
  resources :pages, only: [:show,:create,:destroy,:edit]
  resources :page_fragment_relationships, only: [:new,:create,:update,:destroy]
  match 'page_fragment_relationships/move_fragment_to_page', to: 'page_fragment_relationships#move_fragment_to_page', as: 'move_fragment_to_page'
  match 'articles/:id/:page_number', to: 'pages#show'
  match 'pages/:id/theme/:theme_id', to: 'pages#assign_theme', as: 'assign_theme_to_page'
  resources :fragments
  
  match '/streamline', to: 'static_pages#streamline', as: 'streamline'
  
  match '/staff', to: 'users#index'
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  resources :fragment_images
  match 'search_new_fragment_image', to: 'fragment_images#search_new', as: 'search_new_fragment_image'
  post 'create_from_search', to: 'fragment_images#create_from_search', as: 'create_searched_fragment_image'
  resources :fragment_image_relationships, only: [:new]
  resources :user_box_image_relationships, only:[:new, :create]
  resources :fragment_types, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  match '/box', to: 'box#show'
  resources :bags, only: [:show, :destroy, :edit, :update, :new, :create]
  resources :user_box_fragment_relationships, only: [:new, :create]
  resources :user_box_resource_relationships do
    collection do
      delete 'destroy_multiple'
      put 'update_multiple'
      get 'edit_multiple'
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :public, :publication_date, :title, :user_id, :menu_ordering,:cover_fragment_id
  
  validates :title, presence:true, length:{maximum:160, minimum:3, message: "Enter a title between 3 and 160 characters."}, uniqueness: { case_sensitive: false, message:"Title already used!" }
  validates_presence_of :user_id
  
  has_many :pages, dependent: :destroy
  
  has_many :fragments, through: :pages, source: :fragments

  has_many :menu_entries, dependent: :destroy
  
  belongs_to :user

  def create
    self.pages.build(number:1)
    super
  end
  
  def first_fragment
    if self.pages.any?
      self.pages.order('number ASC').first.fragments.order('ordering_number ASC').first
    end
  end
 
 def cover_fragment
   if not self.cover_fragment_id.nil? and fragment=Fragment.find_by_id(self.cover_fragment_id)
     fragment
   else
     self.first_fragment
   end
 end
 
  def chapters_outline
    result = []
    current_chapter = nil
    sorted_pages = self.pages.order('number ASC')
    sorted_pages.each do |page|
      if not page.name.nil? and page.name.size>0
        result.append({:chapter_title => page.name, :page_number => page.number})
      end
    end
    return result
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  include FragmentsHelper
 
  
  #-----------------------------------------------------Privileges
  before_filter :article_create_filter, only:[:new,:create]
  before_filter :article_destroy_filter, only: :destroy
  before_filter :article_edit_filter, only: [:edit, :update, :set_cover_fragment]
  before_filter :article_view_filter, only: [:show]
  before_filter :article_publish_filter, only: :publish
  
  def new
    @article = Article.new
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @article = Article.create(title: params[:title], user_id: current_user.id)
    if @article.save
      redirect_to edit_article_path(@article)
    else
      flash[:errors] = "There has been some problem creating your article."
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
    @article_editing=true
    @page = @article.pages.order('number ASC').first
    @fragments = @page.ordered_fragments
    @include_all_libraries = true #Quick temporary solution
    @fragment_types = getFragmentTypes(@fragments)
  end

  def update
    @article = Article.find(params[:id])
    #salvataggio articolo
    @article.update_attributes(title: params[:article][:title].gsub(/\r\n/," "))
    flash[:errors] = @article.errors.messages unless @article.errors.empty?
    #salvataggio frammenti    
    params[:fragments].each do |id, fragment|
      tempFrag = Fragment.find(id)
      tempFrag.update_attributes(data:fragment[:data])
      tempFrag.buildResources(fragment) unless fragment[:images].nil?
    end unless params[:fragments].nil?
    #salvataggio pagine/parametri pagina
    params[:pages].each do |id, page|
      tempPage = Page.find(id)
      tempPage.update_attributes(number: page[:number],
                                  name: page[:name].gsub(/\r\n/," "),
                                  theme_id: page[:theme_id]||nil)
      flash[:errors] = tempPage.errors.messages unless tempPage.errors.empty?
    end
    
    respond_to do |format|
      format.js
    end
  end

  def destroy
    # TODO completare
    @article = Article.find(params[:id])
    if @article.destroy
      respond_to do |format|
        format.js
        format.html do
          flash[:success] = "Your article has been deleted"
          redirect_to articles_path
        end
      end
    end
    
  end

  def index
    @articles = current_user.articles.order('updated_at desc').paginate(:page => params[:page], :per_page => 4)
    
    @fragments = article_summaries_fragments(@articles)
    @fragment_types = getFragmentTypes(@fragments)
  end

  def show
    @article = Article.find(params[:id])
    @page = @article.pages.find_by_number(params[:page_number])||@article.pages.order('number ASC').first
    @fragments = @page.ordered_fragments
    @fragment_types = getFragmentTypes(@fragments)
    @show_og_twitter_meta = true
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def publish
    @article = Article.find(params[:id])
    if @article.update_attributes(public:true, publication_date:Time::now)
      flash[:success] = "#{@article.title} published!"
      respond_to do |format|
        format.html do
          @page = @article.pages.find_by_number(params[:page_number])||@article.pages.order('number ASC').first
          @fragments = @page.ordered_fragments
          @fragment_types = getFragmentTypes(@fragments)
          render 'show'
        end
        format.js
      end
    end
  end
  
  def unpublish
    @article = Article.find(params[:id])
    if @article.update_attributes(public:false)
      MenuEntry.find_by_article_id(@article.id).destroy unless MenuEntry.find_by_article_id(@article.id).nil? 
      flash[:success] = "#{@article.title} unpublished!"
      respond_to do |format|
        format.html do
          @page = @article.pages.find_by_number(params[:page_number])||@article.pages.order('number ASC').first
          @fragments = @page.ordered_fragments
          @fragment_types = getFragmentTypes(@fragments)
          render 'show'
        end
        format.js
      end
    end
  end
  
  def set_cover_fragment
    @article = Article.find(params[:id])
    if @fragment = Fragment.find(params[:fragment_id]) and @article.update_attributes(cover_fragment_id:params[:fragment_id])
      flash[:success] = "This fragment will now be displayed as this article's cover"
    else
      flash[:errors]  = "There has been a problem assigning this cover."
    end
    
    respond_to do |format|
      format.js
      format.html
    end
  end
  
  private
  
    def article_create_filter
      if not can_create_articles?
        flash[:errors] = "You're not the boss, you can't create articles."
        redirect_to root_path
      end
    end
    
    def article_edit_filter
      if not can_edit_article?
        flash[:errors] = "You can't edit this article"
        redirect_to root_path
      end
    end
    
    def article_destroy_filter
      if not can_destroy_article?
        flash[:errors] = "You can't destroy this article"
        redirect_to root_path
      end
    end
    
    def article_view_filter
      if not can_view_article?
        flash[:errors] = "You can't view this article"
        redirect_to root_path
      end
    end
  
    def article_publish_filter
      if not can_publish_article?
        flash[:errors] = "You can't publish articles"
        redirect_to root_path
      end
    end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def self.streamline(user=nil)
    if user.nil? then
      first_query = Article.where('public=?', true)
    else
      first_query = Article.where('public=? and user_id=?', true,user.id)
    end
    first_query
  end
  
  def article_summaries_fragments(articles)
    fragments = []
    articles.each do |a|
      if not a.cover_fragment.nil?
        fragments = fragments+[a.cover_fragment]
      end
    end
    return fragments
  end
  
  def in_user_menu(article, user = current_user)
    menu_entry = MenuEntry.where('user_id=? and article_id=?', user, article)
    menu_entry.count>0 ? true : false
  end
  
  #privileges
  def can_create_articles?
    has_role?('superadmin')||has_role?('writer')
  end
  
  def can_destroy_article?(article=Article.find(params[:id]))
    has_role?('superadmin')||article.user == current_user
  end
  
  def can_edit_article?(article=Article.find(params[:id]))
    has_role?('superadmin')||article.user == current_user
  end
  
  def can_view_article?(article=Article.find(params[:id]))
    article.public || has_role?('superadmin') || article.user == current_user || !MenuEntry.find_by_article_id(article.id).nil?
  end
  
  def can_publish_article?(article=Article.find(params[:id]))
    has_role?('superadmin') || (has_role?('publisher')&&article.user == current_user)
  end
end

app/views/articles/_article.html.erb
<% article ||= @article
remote_bool = true
%>
<section class="article_partial resource_partial" id="article_<%= article.id %>">
	<!-- Controls for privileged users -->
	<%= render 'common_partials/editing_header' if can_edit_article?(article)||can_destroy_article?(article)||can_publish_article?(article) %>
	<div class="hide tooltip_content">
		<a class="close">&times;</a>
		<%= render 'articles/article_controls', article:article, remote_bool: true %>
	</div>
	
	<%= render 'articles/article_header', article:article, page_name: false %>
	<div class="article-summary">
		<%= render 'fragments/fragment', fragment: article.cover_fragment unless article.pages.count==0||article.cover_fragment.nil?%>
	</div>
	<footer>
		<%= link_to article_path(article), class:'read_more_link' do %>
			[Read more...]
		<% end %>
	</footer>
</section>

app/views/articles/_article_summaries_styles.html.erb
<%
	article ||= @article
	page = article.pages.order('number ASC').first
	if !page.nil?&&page.fragments.count>0
		fragment = article.first_fragment
		frag_type = fragment.fragment_type
		 
		scss_variables = "$background_color: #ffffff;$foreground_color: #000000;$third_color: #555555;"
		scss_variables = page.theme.getSCSSVariables
		scss_string =<<EOF
#{scss_variables}
#article_#{article.id} {
	.article-summary{
			
	}
	.fragment_container {
		background-color: $background_color;
		color: $foreground_color;
	}
	.fragment_type_#{frag_type.id} { #{frag_type.stylesheet}}
}
EOF
		sass_engine = Sass::Engine.new(scss_string,:syntax => :scss) %>
		<%= sass_engine.render %>
<% end %>

app/views/articles/_fragments_with_contextual.html.erb
<div class="span8">
<% @fragments.each do |frag| %>
	<div class="row">
		<div class="span8">
			<%= render 'fragments/fragment', popover_controls:true, fragment:frag, aside: true %>
		</div>
	</div>
<% end %>
</div>

app/views/articles/_new_article_form.html.erb
<% @article ||= Article.new %>
<%= form_for @article, validate:true do |object| %>
					<fieldset class='control-group <%= @article.errors[:title].any? ? 'error' : '' %>'>
					<%= text_field_tag 'title', @article.title, placeholder:'Your title goes here.', class:'required name', autofocus:true %>
					<span class='help-inline'><%= @article.errors[:title].any? ? @article.errors[:title].first.capitalize : '' %></span>
					</fieldset>

					<div class="form-action">
					<%= submit_tag 'Let\'s get to work!', class:'btn btn-primary', "data-loading-text" => "Toasting..." %>
					</div>
		<% end %>

app/views/articles/_page_controls.html.erb
<div class="page_name_editing_controls">
	<h2 class="page_name"><%= !@page.name.blank? ? @page.name : "(#{@page.chapter || 'Unchaptered Page'})" %></h2>
	<%= link_to '#', class:'btn btn-small hide page_name_edit_button' do %>
		<i class="icon icon-edit"></i>
	<%end%>
	<%= text_field_tag "pages[#{@page.id}][name]", @page.name, placeholder:"( #{@page.chapter || "New Chapter"})", class:'page_name_edit_field' %>
</div>
<div class="page_fragments_controls">
	<ul>
        <li>
	        <%= link_to new_page_fragment_relationship_path(page_id:@page.id), remote:true, class:'btn btn-success' do %>
				<i class="icon icon-white icon-plus"></i> Fragment
			<% end %>
		</li>
        <li>
        	<%= link_to new_page_fragment_relationship_path(page_id:@page.id,from_box:true,add_to_article:true), remote:true, class:"btn btn-primary" do %>
        		 <i class="icon-white icon-folder-open"></i> From Box
        	<% end %>
        </li>
    </ul>
	<%= link_to page_path(@page), remote:true, method: :delete, :data => { :confirm => 'ADD TO YOUR PUZZLE BOX ALL THE FRAGMENTS YOU WANT TO KEEP BEFORE DELETING THIS PAGE. Continue?' }, class:'btn btn-danger' do %>
		<i class="icon icon-white icon-trash"></i> Delete page
	<% end %>
	<%= link_to 'Theme',  choose_theme_path(@page), class: 'btn btn-primary theme_button', remote: true %>

</div>

app/views/articles/_page_hidden_fields.html.erb
<% @article.pages.each do |page| %>
	<%= hidden_field_tag "pages[#{page.id}][number]", page.number, id:"page_#{page.id}_number_field", class:"page_#{page.id}_hidden_field"%>
	<%= hidden_field_tag "pages[#{page.id}][name]", page.name, id:"page_#{page.id}_name_field", class:"page_#{page.id}_hidden_field"%>
	<!-- Page Styling -->
	<%= hidden_field_tag "pages[#{page.id}][theme_id]", page.theme_id, id:"page_#{page.id}_theme_id_field", class:"page_#{page.id}_hidden_field"%>
<% end %>

app/views/articles/_preview_button.html.erb
<%= link_to article_path(id:@article.id, page_number:@page.number), class:'btn article_preview_button' do %>
	<i class="icon icon-eye-open"></i> Preview
<% end %>

app/views/articles/_previous_page_link.html.erb
<%
	if @page!=@article.pages.order('number ASC').first
		@previous_page = @article.pages.find_by_number(@page.number-1)
%>
	<%= link_to article_path(:page_number => @previous_page.number), remote:true, title:"View previous page", class:"previous_page_link" do %>
		< <%= @page.number-1 %>
	<% end %>
<% end %>

app/views/articles/_publish_article_button.html.erb
<%	
	article ||= @article
	republish ||= false
	btn_small ||= false
	remote_bool = true if remote_bool.nil?
%>
<%= link_to publish_article_path(article), remote:remote_bool, class:"btn btn-success #{btn_small ? 'btn-small' : ''} publish_article_button" do %>
	<i class="icon icon-white icon-globe"></i> Publish
<% end unless republish%>

<%= link_to publish_article_path(article), remote:remote_bool, class:"btn btn-info #{btn_small ? 'btn-small' : ''} publish_article_button" do %>
	<i class="icon icon-white icon-repeat"></i> Republish
<% end if republish%>

app/views/articles/_unpublish_article_button.html.erb
<%
	article ||= @article
	btn_small ||= false
	remote_bool = true if remote_bool.nil?
%>
<%= link_to unpublish_article_path(article), remote:remote_bool, class:"btn btn-warning #{btn_small ? 'btn-small' : ''} unpublish_article_button" do %>
	Unpublish
<% end %>

app/views/articles/index.html.erb
<% provide :title, full_title("Your Articles") %>
<% # TODO fare un parziale articles styles che prende il colore della prima pagina e ci compila lo stile del primo frammento di ogni articolo, da usare per renderizzare il sommario dell'articolo
%>
<div class="container">
	<div class="row">
		<header class="offset2 span8">
			<%= pluralize(current_user.articles.count,'article') %>.
		</header>
	</div>
	<div class="row">
		<div class="offset2 span8">
			<div class="centered_content"><%= will_paginate @articles %></div>
				<%= render @articles %>
			<div class="centered_content"><%= will_paginate @articles %></div>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<% provide :title, "New article" %>

<div class="row">
	<div class="offset3 span6">
			<h1>Choose a title,</h1>
			<h2>you can change it later:</h2>
	</div>
</div>
<div class="row">
	<div class="offset3 span6 well">
		<%= render 'articles/new_article_form' %>
	</div>
</div>

app/views/articles/new.js.erb
modalWindow("Insert your title:","<%= escape_javascript(render 'layouts/flash_messages') %><%= escape_javascript(render 'articles/new_article_form') %>");
newArticleValidation();

app/views/articles/show.js.erb
$(".article_view_container").fadeOut(function(){
	$("body").animate({
		backgroundColor:'<%= @page.theme.background_color %>'
	}, function(){
		$(".article_view_fragments_container .fragment_container").popover('hide');
	
		//Updating contents
		$(".article_view_fragments_container").html("<%= escape_javascript(render 'articles/fragments_with_contextual', fragments: @fragments)%>");
		$(".article_header").replaceWith("<%= escape_javascript(render 'articles/article_header') %>");
		
		$(".previous_page_link_container").html("<%= escape_javascript(render 'articles/previous_page_link')%>");
		$(".next_page_link_container").html("<%= escape_javascript(render 'articles/next_page_link')%>");
		
		//Puzzle resources
		<%= render 'fragments/fragments_filling_script' %>
		$("#fragments_styles").html("<%= escape_javascript(render 'common_partials/customizable_styles')%>");
		
		//Fragments initialization
		initializeAllFragments();
		
		$(".article_view_container").fadeIn(function(){
			//Fragments controls initialization
			initializeControlsPopovers();
			initializeArticleViewControls();
			
			//Social interactions re-initialized
                        //FB.init({xfbml:true})
			//twttr.widgets.load();
		});
	});
	
});