config/routes.rb
FragmentsProject::Application.routes.draw do

  resources :libraries

  get 'themes/choose/:page_id', to: 'themes#choose', as: 'choose_theme'
  resources :themes

  resources :menu_entries
  match 'menu_entries/:id/move', to: 'menu_entries#move', as: 'move_menu_entry'
  
  get "puzzle_box/show"

  root to: 'static_pages#home'
  
  resources :users
  resources :user_role_relationships, only: [:create, :destroy]
  resources :sessions, only:[:new,:create,:destroy]
  
  match 'articles/:id/set_cover_fragment/', to: 'articles#set_cover_fragment', as: 'set_article_cover'
  resources :articles
  match 'articles/:id/publish', to: 'articles#publish', as: 'publish_article'
  match 'articles/:id/unpublish', to: 'articles#unpublish', as: 'unpublish_article'
  
  resources :pages, only: [:show,:create,:destroy,:edit]
  resources :page_fragment_relationships, only: [:new,:create,:update,:destroy]
  match 'page_fragment_relationships/move_fragment_to_page', to: 'page_fragment_relationships#move_fragment_to_page', as: 'move_fragment_to_page'
  match 'articles/:id/:page_number', to: 'pages#show'
  match 'pages/:id/theme/:theme_id', to: 'pages#assign_theme', as: 'assign_theme_to_page'
  resources :fragments
  
  match '/streamline', to: 'static_pages#streamline', as: 'streamline'
  
  match '/staff', to: 'users#index'
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  resources :fragment_images
  match 'search_new_fragment_image', to: 'fragment_images#search_new', as: 'search_new_fragment_image'
  post 'create_from_search', to: 'fragment_images#create_from_search', as: 'create_searched_fragment_image'
  resources :fragment_image_relationships, only: [:new]
  resources :user_box_image_relationships, only:[:new, :create]
  resources :fragment_types, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  match '/box', to: 'box#show'
  resources :bags, only: [:show, :destroy, :edit, :update, :new, :create]
  resources :user_box_fragment_relationships, only: [:new, :create]
  resources :user_box_resource_relationships do
    collection do
      delete 'destroy_multiple'
      put 'update_multiple'
      get 'edit_multiple'
    end
  end

end

app/models/library.rb
class Library < ActiveRecord::Base
  attr_accessible :name, :setup

  has_many :fragment_type_library_relationships, dependent: :destroy
  has_many :fragment_types, through: :fragment_type_library_relationships, source: :fragment_type
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @libraries }
    end
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
    @library = Library.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @library }
    end
  end

  # GET /libraries/new
  # GET /libraries/new.json
  def new
    @library = Library.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @library }
    end
  end

  # GET /libraries/1/edit
  def edit
    @library = Library.find(params[:id])
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(params[:library])

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render json: @library, status: :created, location: @library }
      else
        format.html { render action: "new" }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /libraries/1
  # PUT /libraries/1.json
  def update
    @library = Library.find(params[:id])

    respond_to do |format|
      if @library.update_attributes(params[:library])
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library = Library.find(params[:id])
    @library.destroy

    respond_to do |format|
      format.html { redirect_to libraries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
  def can_edit_libraries?(user=current_user)
   has_role?('superadmin')
  end

end

app/views/libraries/_form.html.erb
<%= form_for(@library) do |f| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
      <% @library.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :setup %><br />
    <%= f.text_area :setup %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render 'form' %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<h1>Listing libraries</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Setup</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @libraries.each do |library| %>
  <tr>
    <td><%= library.name %></td>
    <td><%= library.setup %></td>
    <td><%= link_to 'Show', library %></td>
    <td><%= link_to 'Edit', edit_library_path(library) %></td>
    <td><%= link_to 'Destroy', library, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Library', new_library_path %>

app/views/libraries/new.html.erb
<h1>New library</h1>

<%= render 'form' %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @library.name %>
</p>

<p>
  <b>Setup:</b>
  <%= @library.setup %>
</p>


<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>