config/routes.rb
FragmentsProject::Application.routes.draw do

  resources :libraries

  get 'themes/choose/:page_id', to: 'themes#choose', as: 'choose_theme'
  resources :themes

  resources :menu_entries
  match 'menu_entries/:id/move', to: 'menu_entries#move', as: 'move_menu_entry'
  
  get "puzzle_box/show"

  root to: 'static_pages#home'
  
  resources :users
  resources :user_role_relationships, only: [:create, :destroy]
  resources :sessions, only:[:new,:create,:destroy]
  
  match 'articles/:id/set_cover_fragment/', to: 'articles#set_cover_fragment', as: 'set_article_cover'
  resources :articles
  match 'articles/:id/publish', to: 'articles#publish', as: 'publish_article'
  match 'articles/:id/unpublish', to: 'articles#unpublish', as: 'unpublish_article'
  
  resources :pages, only: [:show,:create,:destroy,:edit]
  resources :page_fragment_relationships, only: [:new,:create,:update,:destroy]
  match 'page_fragment_relationships/move_fragment_to_page', to: 'page_fragment_relationships#move_fragment_to_page', as: 'move_fragment_to_page'
  match 'articles/:id/:page_number', to: 'pages#show'
  match 'pages/:id/theme/:theme_id', to: 'pages#assign_theme', as: 'assign_theme_to_page'
  resources :fragments
  
  match '/streamline', to: 'static_pages#streamline', as: 'streamline'
  
  match '/staff', to: 'users#index'
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  resources :fragment_images
  match 'search_new_fragment_image', to: 'fragment_images#search_new', as: 'search_new_fragment_image'
  post 'create_from_search', to: 'fragment_images#create_from_search', as: 'create_searched_fragment_image'
  resources :fragment_image_relationships, only: [:new]
  resources :user_box_image_relationships, only:[:new, :create]
  resources :fragment_types, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  match '/box', to: 'box#show'
  resources :bags, only: [:show, :destroy, :edit, :update, :new, :create]
  resources :user_box_fragment_relationships, only: [:new, :create]
  resources :user_box_resource_relationships do
    collection do
      delete 'destroy_multiple'
      put 'update_multiple'
      get 'edit_multiple'
    end
  end

end

app/models/bag.rb
class Bag < ActiveRecord::Base
    attr_accessible :name, :user_id
    
    validates_presence_of :name, :user_id
    validates_uniqueness_of :user_id, scope: :name
    
    belongs_to :user
    
    has_many :user_box_image_relationships, dependent: :destroy
    has_many :user_box_sound_relationships, dependent: :destroy
    has_many :user_box_video_relationships, dependent: :destroy
    has_many :user_box_untyped_attachment_relationships, dependent: :destroy
    has_many :user_box_fragment_relationships, dependent: :destroy
    
    has_many :box_images, through: :user_box_image_relationships, source: :fragment_image
    has_many :box_sounds, through: :user_box_sounds_relationships, source: :fragment_sound
    has_many :box_videos, through: :user_box_video_relationships, source: :fragment_video
    has_many :box_untyped_attachments, through: :user_box_untype_attachment_relationships, source: :fragment_untyped_attachment
    has_many :box_fragments, through: :user_box_fragment_relationships, source: :fragment
end

app/controllers/bags_controller.rb
class BagsController < ApplicationController
  include BagsHelper
  
  before_filter {@multiple_selection=true}
  before_filter :bag_create_filter, only:[:new,:create]
  before_filter :bag_destroy_filter, only: :destroy
  before_filter :bag_edit_filter, only: [:edit, :update]
  before_filter :bag_view_filter, only: [:show]
  
  def show
    @resources = resourcesFromBag(params[:id],params[:resource_type])
    @current_bag_id = params[:id]
    @multiple_selection = true
    @add_to_article = params[:add_to_article]
    @page_id = params[:page_id]
    respond_to do |format|
      format.js
      format.html
    end
  end
  
  def new
    @bag = current_user.bags.build
    respond_to do |format|
      format.js
    end
  end
  
  def create
    @bag = current_user.bags.build(name:params[:name])
    if @bag.save
      @current_bag_id = @bag.id.to_s
      @resources = resourcesFromBag(@current_bag_id)
      flash[:success] = "Bag #{@bag.name} created!"
      respond_to do |format|
        format.js
      end
    else
      flash[:errors] = "There has been some problem. Try using another name..."
      respond_to do |format|
        format.js { render 'new' }
      end
    end
  end
  
  def edit
    @bag = Bag.find(params[:id])
    @method=:put
    respond_to do |format|
      format.js {render 'new'}
    end
    
  end
  
  def update
    if @bag = Bag.find(params[:id])
      @current_bag_id = @bag.id.to_s
      @resources = resourcesFromBag(@current_bag_id)
      @bag.name=params[:name]
      if @bag.save
        flash[:success] = "Bag renamed!"
      else
        flash[:errors] = "Try using another name"
      end
    end
    respond_to do |format|
      format.js
    end
  end
  
  def destroy
    if Bag.destroy(params[:id])
      @current_bag_id="none"
      flash[:success] = "Bag deleted successfully"
    else
      @current_bag_id=params[:id]
      flash[:error] = "Can't delete this bag"
    end
    respond_to do |format|
        format.html { redirect_to '/box' }
    end
  end
  
  private
    
    def bag_create_filter
        if not can_create_bags?
          flash[:errors] = "You can't create bags."
          redirect_to root_path
        end
      end
      
      def bag_edit_filter
        if not can_edit_bag?
          flash[:errors] = "You can't edit this bag"
          redirect_to root_path
        end
      end
      
      def bag_destroy_filter
        if not can_destroy_bag?
          flash[:errors] = "You can't destroy this bag"
          redirect_to root_path
        end
      end
      
      def bag_view_filter
        if not can_view_bag?
          flash[:errors] = "You can't view this bag"
          redirect_to root_path
        end
      end
  
end

app/helpers/bags_helper.rb
module BagsHelper
  def bagAssignment(params)
     if params[:selected_bag].to_i!=-1 and can_edit_bag?(Bag.find(params[:selected_bag]))
      bag_id = params[:selected_bag]
     else
       bag_id = "-1";
     end
    
      
    if params[:new_bag_name]
      tmp_bag = current_user.bags.find_by_name(params[:new_bag_name]) || current_user.bags.build(name:params[:new_bag_name])
      bag_id = tmp_bag.id if tmp_bag.save
    end
    
    return bag_id
  end
  
  def resourcesFromBag(bag_id=nil,resource_type=nil)   #This needs to be all refactored, it sucks!!!
    if not bag_id.nil?
      if resource_type.nil?
        resources = current_user.bags.find(bag_id).box_fragments + current_user.bags.find(bag_id).box_images
      elsif !resource_type.nil? and resource_type=="fragment_image"
        resources = current_user.bags.find(bag_id).box_images
      elsif !resource_type.nil? and resource_type=="fragment"
        resources = current_user.bags.find(bag_id).box_fragments
      end
      return resources
    else
      if resource_type.nil?
        resources = current_user.box_fragments + current_user.box_images
      elsif !resource_type.nil? and resource_type=="fragment_image"
        resources = current_user.box_images
      elsif !resource_type.nil? and resource_type=="fragment"
        resources = current_user.box_fragments
      end
      return resources
    end
  end
  
  def moveBoxResources(relationships = params[:user_box_resource_relationships], bag_id)
    success = true
    relationships[:fragment_images].each do |id|
      if not UserBoxImageRelationship.find(id).update_attributes(bag_id:bag_id)
        success = false
      end
    end unless relationships[:fragment_images].nil?
    relationships[:fragments].each do |id|
      if not UserBoxFragmentRelationship.find(id).update_attributes(bag_id:bag_id)
        success = false
      end
    end unless relationships[:fragments].nil?
    return success
  end
  
  def destroyBoxResources(relationships = params[:user_box_resource_relationships])
    UserBoxImageRelationship.destroy(relationships[:fragment_images]) unless relationships[:fragment_images].nil?
    UserBoxFragmentRelationship.destroy(relationships[:fragments]) unless relationships[:fragments].nil?
  end
  
  #privileges
  def can_view_bag?(bag=Bag.find(params[:id].to_i))
    has_role?('superadmin')||bag.id!=-1||bag.user == current_user
  end
  
  def can_create_bags?
    has_role?('superadmin')||has_role?('writer')||has_role?('newbie')
  end
  
  def can_destroy_bag?(bag=Bag.find(params[:id].to_i))
    has_role?('superadmin')||bag.id!=-1||bag.user == current_user
  end
  
  def can_edit_bag?(bag=Bag.find(params[:id].to_i))
    has_role?('superadmin')||bag.id!=-1||bag.user == current_user
  end
end

app/views/bags/_bag_related_controls.html.erb
<div id="bag_related_controls" class="box_controls_bar_section">
	<ul>
		<li>
			<% if not @current_bag_id.nil?%>
				<%= link_to 'Delete Bag', bag_path(@current_bag_id), method: :delete, confirm: "Are you sure you want to delete this bag? You will lose all the things you stored in it.", class:"btn btn-mini btn-danger bag_control_icon" if can_destroy_bag?(Bag.find(@current_bag_id)) %>	
			<% end %>
		</li>
		<li>
			<% if not @current_bag_id.nil?%>
				<%= link_to 'Rename Bag', edit_bag_path(@current_bag_id), remote:true, class:"btn btn-mini bag_control_icon" if can_edit_bag?(Bag.find(@current_bag_id)) %>	
			<% end %>
		</li>
	</ul>
</div>

app/views/bags/_box_bags_sidebar_nav.html.erb
<%
	controls=true if controls.nil?
%>
<ul class="nav nav-tabs nav-stacked" id="box_bags_sidebar_nav">
	<li<%= " class='active'" if @current_bag_id.nil? %>><%= link_to 'All', box_path(id:nil,resource_type:@resource_type,add_to_article:@add_to_article, page_id:@page_id), remote: true, id:"bag__link", class:"select_bag_link" %></li>
	<% current_user.bags.each do |bag| %>
		<li<%= " class='active'" if !@current_bag_id.nil? and bag.id == @current_bag_id.to_i %>>
			<%= link_to bag.name, bag_path(id:bag.id,resource_type:@resource_type,add_to_article:@add_to_article, page_id:@page_id), remote: true, id: "bag_#{bag.id}_link", class:"select_bag_link"%>
		</li>
	<% end %>
</ul>
<%= link_to new_bag_path, remote: true, class:"btn btn-small", id:"new_bag_button" do %>
	<i class="icon-black icon-plus"></i>
<% end if controls %>

app/views/bags/_box_resources.html.erb
<%= render 'layouts/flash_messages' %>
<%= form_tag "", id:"box_resources_form", remote: :true do %>
	<%= hidden_field_tag 'bag_id', @current_bag_id.to_s %>
	<ul class="thumbnails">
	 <% @resources.sort_by{ |resource|
        if resource.class.name=="FragmentImage"
          current_user.user_box_image_relationships.find_by_resource_id(resource.id).created_at
        elsif resource.class.name=="Fragment"
          current_user.user_box_fragment_relationships.find_by_resource_id(resource.id).created_at
        end
      }.reverse.each do |resource| 
		 	if resource.class.name=="Fragment" %>
		 		<%= render 'fragments/fragment_summary', fragment: resource %>
		 	<% else %>
		 		<%= render resource %> 
		 	<% end
	 	end
	 %>
	</ul>
<% end %>

app/views/bags/_new_bag_form.html.erb
<% @bag ||= Bag.new
	@method ||= :post
 %>
<div class="bag_edit_form">
<%= form_for @bag, validate:true, remote:true, method: @method do |object| %>
		<fieldset class='control-group <%= @bag.errors[:name].any? ? 'error' : '' %>'>
		<%= text_field_tag 'name', @bag.name, placeholder:'What does it contain?', class:'required name', autofocus:true %>
		<span class='help-inline'><%= @bag.errors[:name].any? ? @bag.errors[:name].first.capitalize : '' %></span>
		</fieldset>

		<div class="form-action">
		<%= submit_tag "Save", class:'btn btn-primary', "data-loading-text" => "Creating..." %>
		</div>
<% end %>
</div>

app/views/bags/_show.js.erb
$("#box_items_controls #bag_related_controls").replaceWith("<%= escape_javascript(render 'bags/bag_related_controls') %>");
$("#box_resources_list_container").slideUp(function(){
	$("#box_resources_list_container").html("<%= escape_javascript(render 'bags/box_resources') %>");
	$("#box_bags_sidebar_nav li").removeClass("active");
	$("#box_bags_sidebar_nav #bag_<%= escape_javascript(@current_bag_id) %>_link").parent("li").addClass("active");
	$("#box_resources_list_container").slideDown();
});

app/views/bags/_update_views.js.erb
//In this view make sure the box view is consistent with user actions
<% if @current_bag_id=="none"||@current_bag_id==nil %>
	$.ajax({
	type: "GET",
	url: "/box",
	});
<% else %>
	$.ajax({
	type: "GET",
	url: "/bags/<%= @current_bag_id %>",
	});
<% end %>
$("#box_bags_sidebar_nav_container").html("<%= escape_javascript(render 'bags/box_bags_sidebar_nav') %>");

app/views/bags/create.js.erb
modalWindow("","<%= escape_javascript(render 'layouts/flash_messages') %>");

//Update anything in the page regarding bags
<%= render 'bags/update_views' %>

app/views/bags/new.js.erb
modalWindow("Choose a name:","<%= escape_javascript(render 'layouts/flash_messages') %><%= escape_javascript(render 'bags/new_bag_form') %>");

app/views/bags/show.js.erb
$("#box_items_controls #bag_related_controls").replaceWith("<%= escape_javascript(render 'bags/bag_related_controls') %>");
$("#box_resources_list_container").slideUp(function(){
	$("#box_resources_list_container").html("<%= escape_javascript(render 'bags/box_resources') %>");
	$("#box_bags_sidebar_nav li").removeClass("active");
	$("#box_bags_sidebar_nav #bag_<%= escape_javascript(@current_bag_id) %>_link").parent("li").addClass("active");
	$("#box_resources_list_container").slideDown();
	initializeControlsPopovers();
});

app/views/bags/update.js.erb
modalWindow("","<%= escape_javascript(render 'layouts/flash_messages') %>");

//Update anything in the page regarding bags
<%= render 'bags/update_views' %>