config/routes.rb
FragmentsProject::Application.routes.draw do

  resources :libraries

  get 'themes/choose/:page_id', to: 'themes#choose', as: 'choose_theme'
  resources :themes

  resources :menu_entries
  match 'menu_entries/:id/move', to: 'menu_entries#move', as: 'move_menu_entry'
  
  get "puzzle_box/show"

  root to: 'static_pages#home'
  
  resources :users
  resources :user_role_relationships, only: [:create, :destroy]
  resources :sessions, only:[:new,:create,:destroy]
  
  match 'articles/:id/set_cover_fragment/', to: 'articles#set_cover_fragment', as: 'set_article_cover'
  resources :articles
  match 'articles/:id/publish', to: 'articles#publish', as: 'publish_article'
  match 'articles/:id/unpublish', to: 'articles#unpublish', as: 'unpublish_article'
  
  resources :pages, only: [:show,:create,:destroy,:edit]
  resources :page_fragment_relationships, only: [:new,:create,:update,:destroy]
  match 'page_fragment_relationships/move_fragment_to_page', to: 'page_fragment_relationships#move_fragment_to_page', as: 'move_fragment_to_page'
  match 'articles/:id/:page_number', to: 'pages#show'
  match 'pages/:id/theme/:theme_id', to: 'pages#assign_theme', as: 'assign_theme_to_page'
  resources :fragments
  
  match '/streamline', to: 'static_pages#streamline', as: 'streamline'
  
  match '/staff', to: 'users#index'
  
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  
  resources :fragment_images
  match 'search_new_fragment_image', to: 'fragment_images#search_new', as: 'search_new_fragment_image'
  post 'create_from_search', to: 'fragment_images#create_from_search', as: 'create_searched_fragment_image'
  resources :fragment_image_relationships, only: [:new]
  resources :user_box_image_relationships, only:[:new, :create]
  resources :fragment_types, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  match '/box', to: 'box#show'
  resources :bags, only: [:show, :destroy, :edit, :update, :new, :create]
  resources :user_box_fragment_relationships, only: [:new, :create]
  resources :user_box_resource_relationships do
    collection do
      delete 'destroy_multiple'
      put 'update_multiple'
      get 'edit_multiple'
    end
  end

end

app/models/menu_entry.rb
class MenuEntry < ActiveRecord::Base
  attr_accessible :title, :link_type, :article_id, :order, :user_id, :link_type
  belongs_to :user
end

app/controllers/menu_entries_controller.rb
class MenuEntriesController < ApplicationController
  include MenuEntriesHelper
  
  #before_filter :menu_entry_create_filter, only:[:new,:create]
  before_filter :menu_entry_destroy_filter, only: :destroy
  before_filter :menu_entry_edit_filter, only: [:update]


  # GET /menu_entries
  # GET /menu_entries.json
  def index
    @menu_entries = MenuEntry.where('user_id=?',params[:user_id] || current_user.id).order('menu_entries.order ASC') #You should retrieve menus by user

    respond_to do |format|
      format.html
    end
  end

  # POST /menu_entries
  # POST /menu_entries.json
  def create
    params[:menu_entry][:order] = MenuEntry.find_all_by_user_id(params[:menu_entry][:user_id]).count
    params[:menu_entry][:title] = Article.find(params[:menu_entry][:article_id]).title
    @menu_entry = MenuEntry.new(params[:menu_entry])
    @article    = Article.find(params[:menu_entry][:article_id])

    respond_to do |format|
      if can_create_menu_entry? and @menu_entry.save #Need to enforce the fact that 'article' type requires an article_id
        flash[:success] = "Article added to your blog's menu!"
        format.html { redirect_to request.referer }
        format.js
      else
        flash[:errors] = "Impossible to add this article to your blog menu. Make sure you have the permissions."
        format.html { redirect_to request.referer }
        format.js
      end
    end
  end

  # PUT /menu_entries/1
  # PUT /menu_entries/1.json
  def update
    @menu_entry = MenuEntry.find(params[:id])

    respond_to do |format|
      if @menu_entry.update_attributes(params[:menu_entry])
        format.html { redirect_to @menu_entry, notice: 'Menu entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu_entry.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def move
    user_id = params[:user_id] || current_user.id
    @moved_menu_entry = MenuEntry.find(params[:id])
    position_left  = @moved_menu_entry.order
    position_taken = params[:new_order].to_i
    if position_taken<position_left 
      increment = 1
      position_taken = [0,position_taken].max 
    else
     increment = -1 
     position_taken  = [position_taken,MenuEntry.all.count-1].min
    end
    MenuEntry.transaction do
      @moved_menu_entry.update_attributes(:order => -1)
      @shifted_menu_entries = MenuEntry.where('menu_entries.order>=? AND menu_entries.order<=?',[position_taken,position_left].min,[position_taken,position_left].max)
      @shifted_menu_entries.each do |entry|
        entry.update_attributes(:order => entry.order+increment) unless entry == @moved_menu_entry
      end
      @moved_menu_entry.update_attributes(:order => position_taken)
    end
    @menu_entries = MenuEntry.where('user_id = ?', user_id).order('menu_entries.order ASC')
    
    respond_to do |format| 
      format.html { render 'index' }
    end
  end

  # DELETE /menu_entries/1
  # DELETE /menu_entries/1.json
  def destroy
    @menu_entry = MenuEntry.find(params[:id])
    @menu_entry.destroy

    respond_to do |format|
      format.html { redirect_to menu_entries_url }
      format.json { head :no_content }
    end
  end
  
  private
    def menu_entry_create_filter
        if not can_create_menu_entry?
          flash[:errors] = "You can't add this link to your menu."
          redirect_to root_path
        end
      end
      
      def menu_entry_edit_filter
        if not can_edit_menu_entry?
          flash[:errors] = "You can't modify this menu."
          redirect_to root_path
        end
      end
      
      def menu_entry_destroy_filter
        if not can_destroy_menu_entry?
          flash[:errors] = "You can't modify this menu"
          redirect_to root_path
        end
      end
      
      def menu_entry_view_filter
        if not can_view_menu_entry?
          flash[:errors] = "You can't modify this menu"
          redirect_to root_path
        end
      end
end

app/helpers/menu_entries_helper.rb
module MenuEntriesHelper
    #privileges
  def can_view_menu_entry?(user_id = params[:user_id]||current_user)
    has_role?('superadmin')||user_id == current_user.id
  end
  
  def can_create_menu_entry?(user=current_user, link_type='article', article_id=params[:menu_entry][:article_id])
    (has_role?('superadmin')||has_role?('writer')) and (not link_type=='article' or Article.find(article_id).user==user)
  end
  
  def can_destroy_menu_entry?(menu_entry=MenuEntry.find(params[:id]))
    has_role?('superadmin')||menu_entry.user_id == current_user.id
  end
  
  def can_edit_menu_entry?(menu_entry=MenuEntry.find(params[:id]))
    has_role?('superadmin')||menu_entry.user_id == current_user.id
  end
end

app/views/menu_entries/_form.html.erb
<%= form_for(@menu_entry) do |f| %>
  <% if @menu_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu_entry.errors.count, "error") %> prohibited this menu_entry from being saved:</h2>

      <ul>
      <% @menu_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br />
    <%= f.number_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :order %><br />
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :link_type %><br />
    <%= f.text_field :link_type %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menu_entries/create.js.erb
modalWindow("","<%= escape_javascript(render 'layouts/flash_messages') %>");
$("#article_<%= @article.id %> .tooltip_content").html("<a class='close'>&times;</a><%= escape_javascript(render 'articles/article_controls', remote_bool: true, article:@article) %>");

app/views/menu_entries/edit.html.erb
<h1>Editing menu_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu_entry %> |
<%= link_to 'Back', menu_entries_path %>

app/views/menu_entries/index.html.erb
<% provide :title, full_title("Edit Menu") %>
<div class="offset1 span6">
	<div class="container-fluid puzzle_box_container" id="puzzle_box_fragments_container">
		<div class="row">
			<div class="span8 offset2">
				<h1>Edit Menu</h1>
				<p>
					Changes will take place immediately.
				</p>
				<p>
					To add an article to your website's menu, navigate to that article and add it via its 'edit' menu.'
				</p>
			</div>
		</div>
		<div class="row">
			<div class="span8 offset2">
				<table>
					<% @menu_entries.each do |menu_entry| %>
					<tr>
						<td><%= link_to menu_entry, confirm: 'Are you sure?', method: :delete do %> <i class="icon-remove"></i> <% end %> </td>
						<td><%= link_to menu_entry.title, article_path(menu_entry.article_id) if menu_entry.link_type == 'article' %></td>
						<td><%= link_to move_menu_entry_path({:new_order=>menu_entry.order-1, :id=>menu_entry.id}) do %> <i class="icon-arrow-up"></i> <% end %> </td>
						<td><%= link_to move_menu_entry_path({:new_order=>menu_entry.order+1, :id=>menu_entry.id}) do %> <i class="icon-arrow-down"></i> <% end %> </td>
					</tr>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/menu_entries/new.html.erb
<h1>New menu_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', menu_entries_path %>

app/views/menu_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Article:</b>
  <%= @menu_entry.article_id %>
</p>

<p>
  <b>Order:</b>
  <%= @menu_entry.order %>
</p>

<p>
  <b>Link type:</b>
  <%= @menu_entry.link_type %>
</p>

<p>
  <b>Title:</b>
  <%= @menu_entry.title %>
</p>


<%= link_to 'Edit', edit_menu_entry_path(@menu_entry) %> |
<%= link_to 'Back', menu_entries_path %>